SRC_DIR = /home/sydney/Documents/cryptographicengineering/CS5580-SABER/SAW_Cryptol_Verification/source_code/individual_functions

BS2POLVECp.bc: $(SRC_DIR)/BS2POLVECp.c
	clang-17 -emit-llvm -g -O1 -c $< -o $@
